version: '3.3'
services:
  node:
    container_name: insight_node
    build: .
    working_dir: /home/node/app
    command:
            - /bin/bash
            - "-c"
            - "npm run-script build && npm install && npm start" #lancement de la commande start du package.json
    env_file:
      - .env #for JWT TOKEN
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'
    networks:
      - insight-network
  mongo:
    container_name: insight_mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - insight-network
networks:
  insight-network:
    driver: bridge
